### DISCUSSION TITLE
vivia博客主题的使用

### DISCUSSION THREAD

**Discussion by RainyL7** [saicaca/hexo-theme-vivia#19] [Q&A] [answered]
横幅怎么显示

**Comment by RainyL7** [comment]
我使用了博主的vivia主题，但是我的没有显示那张横幅图片，我把我能想到的办法都试过了也没有解决，所以想来请问一下博主

**Reply by saicaca** [reply, marked as answer]
横幅图片需要在 `_config.vivia.yml` 里设置启用
```yaml
banner:
  enable: true                  # 启用横幅
  url: /assets/banner.png       # 横幅图片在 `source` 目录内的相对路径
```
