### ISSUE TITLE
color-generate.js 获取config中配置的 “hue” 变量失败

### ISSUE THREAD

**Issue by NekoRectifier** [saicaca/hexo-theme-vivia#10]
# 报错

在 color-generate.js 中
```javascript
hexo.extend.filter.register('stylus:renderer', function(style) {
    let hue = hexo.config.theme_config.hue;
    ...
```

`hue` 变量看起来无法获取，从而导致 css 无法正常生成。报错如下：

```plain
neko@hp822 ~/C/Nya-Blog (main)> hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Asset render failed: css/style.css
TypeError: Cannot read properties of undefined (reading 'hue')
    at Hexo.<anonymous> (/home/neko/Code/Nya-Blog/node_modules/hexo-theme-vivia/scripts/color-generate.js:14:40)
    at Filter.execSync (/home/neko/Code/Nya-Blog/node_modules/hexo/dist/extend/filter.js:72:36)
    at Hexo.execFilterSync (/home/neko/Code/Nya-Blog/node_modules/hexo/dist/hexo/index.js:394:35)
    at Renderer.<anonymous> (/home/neko/Code/Nya-Blog/node_modules/hexo-renderer-stylus/lib/renderer.js:54:24)
    at Renderer.use (/home/neko/Code/Nya-Blog/node_modules/stylus/lib/renderer.js:204:6)
    at Hexo.stylusFn (/home/neko/Code/Nya-Blog/node_modules/hexo-renderer-stylus/lib/renderer.js:54:6)
    at Hexo.tryCatcher (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/usr/lib/node_modules/hexo-cli/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/neko/Code/Nya-Blog/node_modules/hexo/dist/hexo/render.js:73:28
    at tryCatcher (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/neko/Code/Nya-Blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```

主题通过 `npm install hexo-theme-vivia` 安装。  

## 主题配置文件 

```yaml
# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon:                   # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: false            # Display banner
  url: /assets/banner.png
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 270                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5

# Personal info
avatar: 
author: NekoRectifer
subtitle: This is the subtitle
links:
  - name: Twitter
    icon: fa-brands fa-twitter      # Find icon codes at https://fontawesome.com/search
    url: https://twitter.com
  - name: Steam
    icon: fa-brands fa-steam
    url: https://store.steampowered.com
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com

comment:
  valine:
    enable: false
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details

```

# 解决方法

将 hue 手动指定为 `270` 后，页面 css 正常生成。  
`let hue = 270;`
