### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by xyzfrozen** [saicaca/hexo-theme-vivia#30]
在哪里开 Markdown 啊

**Comment by xyzfrozen** [comment]
还有 Personal info 的 网页 icon 替换了，但是还是不能显示

```
links:
  - name: Cnblogs
    icon: fa-solid fa-blog  # Find icon codes at https://fontawesome.com/search
    url: https://www.cnblogs.com/xyzfrozen
  - name: Luogu
    icon: fa-solid fa-l
    url: https://www.luogu.com.cn
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com
```

这样只有 Github 的可以显示

**Comment by LynxCatTheThird** [comment]
> 在哪里开 Markdown 啊

Markdown 为 Hexo 原生支持，不存在所谓的“开”。如果您遇到了渲染问题，请：

1. 检查语法（尤其是中英文字符和空格）
2. 检查渲染器

---

> 还有 Personal info 的 网页 icon 替换了，但是还是不能显示
> 
> 这样只有 Github 的可以显示

这是因为您配置错了。请不要想当然地编辑，到[这里](https://fontawesome.com/search)查询一下再更改。

**Comment by xyzfrozen** [comment]
> > 在哪里开 Markdown 啊
> 
> Markdown 为 Hexo 原生支持，不存在所谓的“开”。如果您遇到了渲染问题，请：
> 
> 1. 检查语法（尤其是中英文字符和空格）
> 2. 检查渲染器
> 
> > 还有 Personal info 的 网页 icon 替换了，但是还是不能显示
> > 这样只有 Github 的可以显示
> 
> 这是因为您配置错了。请不要想当然地编辑，到[这里](https://fontawesome.com/search)查询一下再更改。

# Q1

我的意思是类似

```
plugins:
    mathjax: true
```

这样的东西主题里面好像没找到，这个是否修改有影响吗？

渲染器更换为 $kramed$ 了，并且修改了 $\text{escape，em}$

这是本地的 $inline.js$

```
var _utils = require('../utils');
var replace = _utils.replace;
var merge = _utils.merge;
var noop = _utils.noop;

/**
 * Inline-Level Grammar
 */

var inline = {
  escape: /^\\([`*\[\]()#$+\-.!_>])/,
  autolink: /^<([^ >]+(@|:\/)[^ >]+)>/,
  url: noop,
  html: /^<!--[\s\S]*?-->|^<(\w+(?!:\/|[^\w\s@]*@)\b)*?(?:"[^"]*"|'[^']*'|[^'">])*?>([\s\S]*?)?<\/\1>|^<(\w+(?!:\/|[^\w\s@]*@)\b)(?:"[^"]*"|'[^']*'|[^'">])*?>/,
  link: /^!?\[(inside)\]\(href\)/,
  reflink: /^!?\[(inside)\]\s*\[([^\]]*)\]/,
  nolink: /^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,
  reffn: /^!?\[\^(inside)\]/,
  strong: /^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
  em: /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
  code: /^(`+)\s*([\s\S]*?[^`])\s*\1(?!`)/,
  br: /^ {2,}\n(?!\s*$)/,
  del: noop,
  text: /^[\s\S]+?(?=[\\<!\[_*`$]| {2,}\n|$)/,
  math: /^\$\$\s*([\s\S]*?[^\$])\s*\$\$(?!\$)/,
};

inline._inside = /(?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*/;
inline._href = /\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/;

inline.link = replace(inline.link)
  ('inside', inline._inside)
  ('href', inline._href)
  ();

inline.reflink = replace(inline.reflink)
  ('inside', inline._inside)
  ();

inline.reffn = replace(inline.reffn)
  ('inside', inline._inside)
  ();

/**
 * Normal Inline Grammar
 */

inline.normal = merge({}, inline);

/**
 * Pedantic Inline Grammar
 */

inline.pedantic = merge({}, inline.normal, {
  strong: /^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,
  em: /^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/
});

/**
 * GFM Inline Grammar
 */

inline.gfm = merge({}, inline.normal, {
  escape: replace(inline.escape)('])', '~|])')(),
  url: /^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])/,
  del: /^~~(?=\S)([\s\S]*?\S)~~/,
  text: replace(inline.text)
    (']|', '~]|')
    ('|', '|https?://|')
    ()
});

/**
 * GitBook Grammar
 */
inline.gitbook = merge({}, inline.gfm, {
  // Template variable
  tplvar: /^{{\s*(.*?)\s*(?=}})}}/,

  // Template expression
  tplexpr: /^{%\s*(.*?)\s*(?=%})%}/,
});
inline.gitbook.text = replace(inline.gfm.text)
  ('~]|', '~]|'+inline.gitbook.tplvar.source+'|'+inline.gitbook.tplexpr.source+'|')
  ();

/**
 * GFM + Line Breaks Inline Grammar
 */

inline.breaks = merge({}, inline.gfm, {
  br: replace(inline.br)('{2,}', '*')(),
  text: replace(inline.gfm.text)('{2,}', '*')()
});

module.exports = inline;
```

还是没法触发成功，大佬能否看看

---

# Q2

$icon$ 配置我是从 fontawesome 直接复制的源代码

```
<i class="fa-brands fa-github"></i>
```

```
<i class="fa-solid fa-l"></i>
```

本地修改为

```
links:
  - name: Cnblogs
    icon: fa-solid fa-blog  # Find icon codes at https://fontawesome.com/search
    url: https://www.cnblogs.com/xyzfrozen
  - name: Luogu
    icon: fa-solid fa-l
    url: https://www.luogu.com.cn
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com
```

就是按照这个渲染成功的 $Github$ 改的，是不能这样改吗

**Comment by xyzfrozen** [comment]
个人网站 https://xyzfrozen.github.io/

**Comment by LynxCatTheThird** [comment]
### Q1

看不懂 inline.js……

---

### Q2

我这边可以显示，但是我对主题进行了修改（参见#29）。可能是因为主题的字体不全，导致找不到某些符号……？
![image](https://github.com/saicaca/hexo-theme-vivia/assets/103188954/bfbe2b0e-821c-409d-a7de-664b8511ab0d)

**Comment by saicaca** [comment]
Q1. 你说的这个应该是 hexo-renderer-markdown-it 这个渲染器的配置，我觉得这个和主题没有什么关系，主题没有指定渲染器，你可以自行把 Hexo 的渲染器换成 hexo-renderer-markdown-it，在 `_config.yml` 中填写相关配置。

Q2. 你的配置没有问题，但我看到你网站上的图标代码和你发的配置不一样。
![image](https://github.com/saicaca/hexo-theme-vivia/assets/25200299/dff91b1a-2b74-402d-9aa3-2f7c1ac5d038)
应该是因为你 Hexo 的本地缓存没有更新，你可以尝试先执行 `hexo clean` 删除缓存再重新部署。

**Comment by xyzfrozen** [comment]
第二个问题解决了
第一个换了渲染器，但是公式重复了
貌似是 $Katex$ 和 $Mathjax$ 重复了，这个怎么办啊
[这篇文章](https://www.zhihu.com/question/267011398#:~:text=3%20%E4%BA%BA%20%E8%B5%9E%E5%90%8C%E4%BA%86%E8%AF%A5%E5%9B%9E%E7%AD%94%20%E4%BD%A0%E5%BA%94%E8%AF%A5%E5%AE%89%E8%A3%85%E4%BA%86%20hexo-renderer-markdown-it-plus,%E5%90%A7%EF%BC%9F%20%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E7%9A%84Katex%E4%B8%8E%E4%BD%A0%E7%9A%84mathJax%E9%87%8D%E5%A4%8D%E4%BA%86%EF%BC%8C%E6%89%80%E4%BB%A5%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%A4%E4%B8%AA%E3%80%82%20%E6%8A%8AMathJax%20Support%E4%B8%ADtrue%E6%94%B9%E6%88%90false%2C%20%E6%96%87%E7%AB%A0%E5%A4%B4%E9%83%A8%E4%B9%9F%E4%B8%8D%E5%86%8D%E9%9C%80%E8%A6%81%E6%B7%BB%E5%8A%A0%20mathjax%3Dtrue)
说的  把MathJax Support中true改成false 是什么意思啊

**Comment by xyzfrozen** [comment]
```
# Math
math:                        
  katex:
    enable: true             
    copytex: true            
    mhchem: false            
  mathjax:
    enable: false   
```

关掉 $mathjax$ 也没用
