### ISSUE TITLE
font-awesome图标丢失

### ISSUE THREAD

**Issue by DaydreamerH** [saicaca/hexo-theme-vivia#49]
font-awesome的图标发生丢失
![image](https://github.com/saicaca/hexo-theme-vivia/assets/113689002/63b5a899-acb7-4c14-9c21-d6bc614a8832)
```
links:
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/DaydreamerH
  - name: Email
    icon: fa-brands fa-envelop
    url: xxx
```
同样也出现在末尾翻页条处
![image](https://github.com/saicaca/hexo-theme-vivia/assets/113689002/11005afd-20a7-46a6-b0fe-3e641ac03f35)
对应网站：https://daydreamerh.github.io/

获取图标报错如下：
![image](https://github.com/saicaca/hexo-theme-vivia/assets/113689002/5872511c-3952-4098-b833-641628d2d07f)
显示跨域问题，是指定图标网站不公开资源了嘛？
（像是miku在引流
小白不懂，求大佬指教
