### ISSUE TITLE
Hue not applying / 色调不适用

### ISSUE THREAD

**Issue by Unbloated** [saicaca/hexo-theme-vivia#81]
First of all, thanks alot for the theme, it's really pretty! / 首先，非常感谢你的主题，它真的很漂亮！

It seems like even thought I keep setting the hue and doing `hexo g`, I keep seeing the default color on my website.
看来，即使我不断设置色调并进行 “`hexo g` ”操作，我在网站上看到的仍然是默认颜色。

![image](https://github.com/user-attachments/assets/6a289cdd-32f4-4de0-afeb-314a9d99a81c)

Here's what is happening, versus what is supposed to happen / 以下是正在发生的事情与应该发生的事情的对比情况 :
![image](https://github.com/user-attachments/assets/be98d003-b55e-4449-8b64-1494d4ca7d18)
_What currently happens, the hue is not set even thought it's written in the config / 目前发生的情况是，色调没有设置，即使配置中已写明_ 

![image](https://github.com/user-attachments/assets/4248204e-f75d-4374-a0cc-7490e0b165c6)
_What it should have looked like, meanwhile `previewMode: true` is currently enabled / 在当前启用 `previewMode：true ` 的情况下，它应该是什么样子的_

## _config.vivia.yml
```yml
# Header
menu:                      # Links in the navigation bar
  Home: /
  Archives: /archives
  About: https://unbloated.lol
rss: /

home:
  style: detail           # default, detail

favicon: /favicon.png                  # Path to the custom favicon relative to /source (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true                  # Display banner
  url: /banner.jpg                # Path to the banner image relative to /source. Web url is also supported
  position: center               # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true               # Display banner on all pages instead of only the home page

# Appearance
hue: 0                        # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)
                                 # Visit `saicaca.github.io/vivia-preview` to preview the theme color
previewMode: false

# Personal info
avatar: /avatar.png                            # Path to the avatar image relative to /source
author: Unbloated
subtitle: Silly odd but curious champ.
links:
  - name: Matrix
    icon: fa-solid fa-comment          # Find icon codes at https://fontawesome.com/search
    url: https://matrix.to/#/@unbloated:matrix.org
  - name: Steam
    icon: fa-brands fa-steam
    url: https://steamcommunity.com/id/unbloated
  - name: Website
    icon: fa-solid fa-link
    url: https://unbloated.lol

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
#      - archive
#      - recent_posts

# Sidebar Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # Maximum depth of categories displayed in the widget (null for unlimited)

# Third-party comment system
comment:
  valine:
    enable: false         # Enable Valine comment system
    appId: 
    appKey: 
    placeholder: Just go go
    pageSize: 10
    highlight: true
    serverURLs: 
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
  twikoo:
    enable: false          # Enable Twikoo comment system
    envID:
    region:
    path: location.pathname
    lang:
    # See also: https://github.com/imaegoo/twikoo

#Analytics
gauges_analytics: false
google_analytics: false #UA-xxxxxx
baidu_analytics: false # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
# analytics are bad :(
```

## _config.yml
```yml
title: Unbloated's Blog
subtitle: 'Yes, really!'
description: "Hey there! You just stumbled across my blog. If you're the sort of being bored, come here check out my stuff!"
keywords: null
author: Unbloated
language: en
timezone: ''
url: https://unbloated.lol
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: DD-MM-YYYY
time_format: HH:mm:ss
updated_option: mtime
per_page: 0
pagination_dir: page
include: null
exclude: null
ignore: null
theme: vivia
deploy:
  type: ''
```

_中文部分是用翻译器翻译的，所以可能不准确，如果有不明白的地方请告诉我，非常抱歉！_
